# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('years_of_service', models.CharField(max_length=3)),
                ('jacket', models.CharField(max_length=30)),
                ('jacket_size', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('team_captain', models.CharField(max_length=30)),
            ],
        ),
    ]
