# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='z_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
