# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161019_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_event', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='team_captain',
        ),
        migrations.AddField(
            model_name='attende',
            name='team_captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='api.Volunteer'),
        ),
        migrations.AddField(
            model_name='attende',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='api.Volunteer'),
        ),
    ]
