# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161019_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='jacket',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='years_of_service',
            field=models.IntegerField(),
        ),
    ]
