# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161028_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_event', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attende',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='team_captain',
        ),
        migrations.RemoveField(
            model_name='attende',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street',
        ),
        migrations.RemoveField(
            model_name='event',
            name='z_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Attende',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='team_captain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='api.Volunteer'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='api.Volunteer'),
        ),
    ]
