# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161107_0311'),
        ('api', '0006_auto_20161020_0038'),
    ]

    operations = [
    ]
