# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20161114_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='jacket',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='years_of_service',
            field=models.CharField(max_length=3),
        ),
    ]
