# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161109_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', related_query_name='event', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='api.Volunteer'),
        ),
    ]
