# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161114_0228'),
        ('api', '0008_auto_20161109_0206'),
    ]

    operations = [
    ]
