# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20161116_1504'),
        ('api', '0009_auto_20161127_0240'),
    ]

    operations = [
    ]
