# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20161201_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='csv',
            field=models.FileField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
