# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161206_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='csv',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
