# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161206_0829'),
        ('api', '0013_auto_20161206_0617'),
    ]

    operations = [
    ]
