# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20161206_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_captain',
            name='event',
        ),
        migrations.RemoveField(
            model_name='team_captain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team_captain',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='Team_Captain',
        ),
    ]
