# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20161207_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='team_cap_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
