# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_attendee_team_cap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='at_event',
            field=models.IntegerField(default=0),
        ),
    ]
