# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20161209_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='at_event',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='team_cap_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='jacket',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='jacket_size',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='years_of_service',
        ),
        migrations.AddField(
            model_name='attendee',
            name='assignment_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='general_event_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='job_descrip',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='specific_event_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='state',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
