# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='general_event_id',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='specific_event_id',
        ),
    ]
