# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
    ]
